export const typeColors: { [key: string]: string } = {
    normal: 'bg-gray-400 text-white',
    fire: 'bg-red-500 text-white',
    water: 'bg-blue-500 text-white',
    grass: 'bg-green-500 text-white',
    electric: 'bg-yellow-400 text-white',
    ice: 'bg-blue-300 text-black',
    fighting: 'bg-orange-500 text-white',
    poison: 'bg-purple-500 text-white',
    ground: 'bg-yellow-700 text-white',
    flying: 'bg-indigo-400 text-white',
    psychic: 'bg-pink-500 text-white',
    bug: 'bg-green-700 text-white',
    rock: 'bg-yellow-800 text-white',
    ghost: 'bg-purple-800 text-white',
    dark: 'bg-gray-700 text-white',
    dragon: 'bg-indigo-800 text-white',
    steel: 'bg-gray-500 text-white',
    fairy: 'bg-pink-300 text-black',
  };
  